FROM python:3.12-slim
WORKDIR /app
COPY requirements.runtime.lock .
RUN pip install --no-cache-dir -r requirements.runtime.lock
COPY . .
RUN pip install --no-cache-dir --no-deps -e .
CMD ["celery", "-A", "apps.worker.main:celery_app", "worker", "--loglevel=INFO"]
