from __future__ import annotations

from typing import Protocol
from uuid import UUID

from invoiceops.domain.entities import AuditEvent, OutboxEvent, Prediction, ReviewDecision, Ticket


class Classifier(Protocol):
    model_version: str

    def predict(self, text: str, *, sanitized: bool = True):
        ...


class Repository(Protocol):
    def add_ticket(self, ticket: Ticket) -> None: ...
    def get_ticket(self, ticket_id: UUID) -> Ticket | None: ...
    def get_ticket_by_request(self, request_id: str) -> Ticket | None: ...
    def delete_ticket(self, ticket_id: UUID) -> None: ...
    def add_prediction(self, prediction: Prediction) -> None: ...
    def get_prediction(self, ticket_id: UUID) -> Prediction | None: ...
    def add_review(self, review: ReviewDecision) -> None: ...
    def add_audit(self, event: AuditEvent) -> None: ...
    def add_outbox(self, event: OutboxEvent) -> None: ...
